apiVersion: v1
kind: Namespace
metadata:
  name: Praveen-test-1
---

apiVersion: Praveen.alpha.coveros.com/v1alpha1
kind: S3
metadata:
  name: s3-bucket
  namespace: Praveen-test-1
  labels:
    app: yourAppName
s3Specs:
  existenceCheckAfterMins: 1
  bucketName: Praveen-test-bucket-1
  region: us-east-1
  newUserAsSecret:
    accessPolicy: "arn:aws:iam::aws:policy/AdministratorAccess"
    secretName: aws-creds
